version: '3.9'

services:
  nestjs-api-prod:
    container_name: nestjs-api-production
    env_file:
      - .env
    image: $ApiImageTag
    # networks:
    #   - nestjs-network-prod
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KEYCLOAK_ADMIN_EMAIL=${KEYCLOAK_ADMIN_EMAIL}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
    restart: on-failure

